---
deployment:
  tasks:
    - export DEPLOYPATH=/home/workkesiswaan/public_html/
    - /bin/cp -R Teacher $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R auth $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH